import { useState,useEffect } from "react";
import axios from "axios";
import MovieDisplay from "./movieDisplay";
import MovieSearch from "./movieSearch";
import '../css/moviesDisplay.css'; 
import { useSelector,useDispatch } from "react-redux";
import { UPDATEMOVIELIST } from "../actions/movielist";
import { APIADD } from "../actions/apicallcounter";
const MovieMain = () => {
    const dark = [
        {
            "title": "Judah Friedlander: America Is the Greatest Country in the United States",
            "img": "http://occ-0-2851-38.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABY8EhHB3JyKlaC3GTuBv_U7cenvUVPnG38E-v60iGeRnnChPt8fZ9XpU50PJl9IcH0e5FMNTM8BNBGvHddpXJszza-DlC81QBZYKWLoiuyJnpYMtbzvY5Q-w4FE.jpg?r=b9d",
            "title_type": "movie",
            "netflix_id": 80208273,
            "synopsis": "Deadpan comic and self-proclaimed world champion Judah Friedlander performs over several nights in New York, explaining why America is No. 1.",
            "rating": "0",
            "year": "2017",
            "runtime": "5066",
            "imdb_id": "notfound",
            "poster": "",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2017-10-31"
        },
        {
            "title": "HDR sRGB Graphics Test (400 nits)",
            "img": "http://occ-2-1168-1217.1.nflxso.net/art/7cd41/b8af11eb7abf57dc66caf8281c73fe4fe027cd41.jpg",
            "title_type": "series",
            "netflix_id": 81014625,
            "synopsis": " Series of sRGB graphics graded to 400 nits in a Dolby Vision container.",
            "rating": "0",
            "year": "2018",
            "runtime": "0",
            "imdb_id": "notfound",
            "poster": "",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2018-07-06"
        },
        {
            "title": "A Love So Beautiful",
            "img": "https://occ-0-2773-2774.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABQdK7ZJ_13hQaqAKwheZKI0aoEDHL8HSNEssCsJtiYrrclR4Z-eAqXC90mozFexPW32ORYTdhuliKK1U3Z7crz0meg.jpg?r=750",
            "title_type": "series",
            "netflix_id": 80239640,
            "synopsis": "The ups and downs of school, family and growing up test the affection between a budding artist and her handsome but indifferent classmate and neighbor.",
            "rating": "0",
            "year": "2017",
            "runtime": "0",
            "imdb_id": "notfound",
            "poster": "",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2018-04-20"
        },
        {
            "title": "72 Cutest Animals",
            "img": "https://occ-0-2851-38.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABRhrKQY4xyiiiz7DkGsSD9TMvj9A2a5s0brdoZ45SubFY5oZdjOtWW7o1TRRqthFfLZHYjU7fCj1TWK4p_s9oY_pag.jpg?r=cec",
            "title_type": "series",
            "netflix_id": 80104022,
            "synopsis": "This series examines the nature of cuteness and how adorability helps some animal species to survive and thrive in a variety of environments.",
            "rating": "3.064516",
            "year": "2016",
            "runtime": "0",
            "imdb_id": "notfound",
            "poster": "",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2016-06-01"
        },
        {
            "title": "Fastest Car",
            "img": "https://occ-0-2851-38.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABZjyGtGygznIW58bYC6_YNhxeKRoMGyT27XaHE_L_chk68iojyIchjH7nR6ILhEQjUq6L5R5mDFppLgegOotLvn79XMYkZa932tyw9_7oirHg4-RtCC9SIaCPqg.jpg?r=1c6",
            "title_type": "series",
            "netflix_id": 80190009,
            "synopsis": "The drivers of exotic supercars put their street cred on the line against deceptively fast sleeper cars built and modified by true gearheads.",
            "rating": "0",
            "year": "2018",
            "runtime": "0",
            "imdb_id": "notfound",
            "poster": "",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2018-04-06"
        },
        {
            "title": "ElectricEye Test",
            "img": "https://scdn.nflximg.net/ipl/18608/6bc80f43da7c0ff3191924ed8a3300b1bbbbf2b3.jpg",
            "title_type": "series",
            "netflix_id": 80103310,
            "synopsis": "Place holder for Synopsis",
            "rating": "3.125",
            "year": "2016",
            "runtime": "0",
            "imdb_id": "notfound",
            "poster": "",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2016-03-24"
        },
        {
            "title": "Crayon Shin-chan the Movie: Serious Battle! Robot Dad Strikes Back",
            "img": "https://occ-0-2772-1007.1.nflxso.net/art/fb025/eba56567f12531d19193e43da985489431dfb025.jpg",
            "title_type": "movie",
            "netflix_id": 80242794,
            "synopsis": "A diabolical plot to empower pushover dads causes Shin-chan&#39;s father to return home as a robot. The Nohara family bond is about to be put to the test!",
            "rating": "0",
            "year": "2014",
            "runtime": "5816",
            "imdb_id": "notfound",
            "poster": "",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2018-04-07"
        },
        {
            "title": "Friend Game",
            "img": "https://occ-0-1007-1360.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABUQqCYe1KyTPx3x2mC-MBLNN8dMj6fuxqEch_k_r2oZNCgSwWkN5z1R7yA7pXm3ufX-Ocd8ENGWWMPKgxADZsEdfQA.jpg?r=29b",
            "title_type": "movie",
            "netflix_id": 81013280,
            "synopsis": "The test of true friendship continues as five classmates awake to the next round of the sadistic game to help repay a debt incurred by one of them.",
            "rating": "0",
            "year": "2017",
            "runtime": "5894",
            "imdb_id": "tt6127014",
            "poster": "N/A",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2018-09-01"
        },
        {
            "title": "Sober Companion",
            "img": "https://occ-0-3420-32.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABfwcNxchwthjCkR0YvXfbfAnxTK5qVTDw4vBbNCoHb8aVufQIzbProAEffpqhbcrNLlax8IZX8CZyfqEG_z0b4hrNg.jpg?r=4bb",
            "title_type": "series",
            "netflix_id": 81313137,
            "synopsis": "One year clean, a man embarks on a new career as a sober companion and finds that his eccentric clients put his sobriety — and sanity — to the test.",
            "rating": "0",
            "year": "2016",
            "runtime": "0",
            "imdb_id": "tt3576760",
            "poster": "",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2021-01-28"
        },
        {
            "title": "Intregalde",
            "img": "https://occ-0-5571-1490.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABXH9W_dJivQmsM6rupRzusKhUbOnp7A_zLHdsjvJLPiXFLONAvWj26enLGJv5_gqFfZBgq9KL6p28K7Mi6_HmPZ3uw.jpg?r=f8a",
            "title_type": "movie",
            "netflix_id": 81506219,
            "synopsis": "Three volunteer workers get stranded in the woods during an attempt to bring aid supplies to rural areas, putting their notions of charity to the test.",
            "rating": "0",
            "year": "2021",
            "runtime": "6244",
            "imdb_id": "tt14050808",
            "poster": "https://m.media-amazon.com/images/M/MV5BOThlYjExMzQtNTY0Ni00OWFjLTg5YzYtMzk2NjgzNWRlNDliXkEyXkFqcGdeQXVyMTI5MjgwMjgw._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2021-10-01"
        },
        {
            "title": "Pantai Norasingha",
            "img": "https://occ-0-58-2773.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABdHkK0kydCg12NxrBeo8RDSUaySrP30tVzC1m8d2C8JOXvI-Ya1Dvi5oNg3QOqUrcUyUE5PgX7up6mC-1Z1PzLCirA.jpg?r=b10",
            "title_type": "movie",
            "netflix_id": 81238558,
            "synopsis": "After a king promotes a commoner to helm his royal barge, a maritime accident will test the law and challenge the limits of their unique friendship.",
            "rating": "0",
            "year": "2015",
            "runtime": "9925",
            "imdb_id": "tt6448036",
            "poster": "",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2020-07-12"
        },
        {
            "title": "Love Is War",
            "img": "http://occ-0-1490-1489.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABfraf92xSL5cL-lAqN9o5K6DYe6-LFxVoYkSS01eFZNXO2qtpSAB-RcULUbqr9x4Rzo-r7tioE5H4nF6u8mrEYDe0A.jpg?r=983",
            "title_type": "movie",
            "netflix_id": 81270671,
            "synopsis": "An adoring couple elects to test the strength of their marriage when they run against each other for the office of state governor.",
            "rating": "0",
            "year": "2019",
            "runtime": "6682",
            "imdb_id": "tt10799940",
            "poster": "https://m.media-amazon.com/images/M/MV5BYmE0ZGE2MTAtZDY0YS00YjQyLTk2YTEtZTU0NTBlODE2ZDY0XkEyXkFqcGdeQXVyMjE2NzE4OTQ@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2020-04-29"
        },
        {
            "title": "Oga Bolaji",
            "img": "https://occ-0-3174-32.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABemkzGccgk2JpTom-QgP3k2tOhdNr83Elh-a9mxXxFsQ-JJK4HxXuj6eGWnP-AHkMMPX-gxhUYjRSoYqWPOfx0K3kQ.jpg?r=e79",
            "title_type": "movie",
            "netflix_id": 81463092,
            "synopsis": "Retired and in his 40s, a happy-go-lucky musician crosses paths with a young girl, changing his simple life and putting his resilience to the test.",
            "rating": "0",
            "year": "2018",
            "runtime": "5483",
            "imdb_id": "tt8847418",
            "poster": "https://m.media-amazon.com/images/M/MV5BNWRiNzJlM2UtZDM0ZC00NDQzLThjMTMtYTk2NzE3NmM1Zjg3XkEyXkFqcGdeQXVyODg4NDI4OTU@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2021-11-03"
        },
        {
            "title": "The Fastest",
            "img": "https://occ-0-1373-2567.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABfyO9EBu4JpTaLxpo3Xw1GcRg0HW95Y_qRlnKf8KTzrgDSCl5X1tfu5YUC9Es3GlJmjebnBUEUkKvycUY-bTbc9nHip4kA790dGX2ueyAbsdCna-dW2RejCyOlI.jpg?r=b85",
            "title_type": "series",
            "netflix_id": 81311852,
            "synopsis": "In this unpredictable and thrilling racing competition, drivers from the Middle East with something to prove battle on the track for a cash prize.",
            "rating": "0",
            "year": "2021",
            "runtime": "0",
            "imdb_id": "tt15779034",
            "poster": "0",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2021-11-23"
        },
        {
            "title": "Harvie And The Magic Museum",
            "img": "https://occ-0-1489-1490.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABb-Xrh7MbMMmUOff97LfHgJJdSv7LzB_Z6lTpCDSFU0n5LcasqXQTSY5qs_x4r1gUuEn9lAHAjXHyy1uptnhvYtXzg.jpg?r=51f",
            "title_type": "movie",
            "netflix_id": 81238455,
            "synopsis": "A video game whiz must put his skills to the test to save an old puppet museum and his city from a power-hungry villain who suddenly returns.",
            "rating": "0",
            "year": "2017",
            "runtime": "5176",
            "imdb_id": "tt6489160",
            "poster": "https://m.media-amazon.com/images/M/MV5BYjc4ZDE5N2UtODFjNi00OGZhLTllZWQtNDZmODE5ZmI0YjdjXkEyXkFqcGdeQXVyMjIxMzMyMQ@@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2020-12-23"
        },
        {
            "title": "Kucch To Hai",
            "img": "https://occ-0-2851-38.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABRKBu-7xqnBqfjx9ES1umjAK5JTXGZM-Fu8alDx_lz7O_N0djJ04yihDMhy49qLdymx-CNpDU40BHuAQWdnFMrm1mg.jpg?r=6b9",
            "title_type": "movie",
            "netflix_id": 70007056,
            "synopsis": "A student tries to steal a test from a teacher&#39;s home, leaving him for dead after an accident. A string of murders may be the professor&#39;s revenge.",
            "rating": "2.3060346",
            "year": "2003",
            "runtime": "8135",
            "imdb_id": "tt0348662",
            "poster": "http://ia.media-imdb.com/images/M/MV5BMTU3NjU2MTEzNF5BMl5BanBnXkFtZTcwMjYwMDQzMg@@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2016-01-06"
        },
        {
            "title": "Far til fire: Tilbage til naturen",
            "img": "https://occ-0-1501-1500.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABYrK9jc9ALiPGDHBv_2_JOFiV2jLlPNMPmzCq7f-jAROwXLC8oZazai82aZHjDeyFp1ykfMrRSpJSxrEFZas3XLpqg.jpg?r=667",
            "title_type": "movie",
            "netflix_id": 70273000,
            "synopsis": "What is the difference between a moose and a bear? Dad&#39;s outdoor abilities are put to the test when the family goes on a weekend trip to Sweden.",
            "rating": "0",
            "year": "2011",
            "runtime": "4764",
            "imdb_id": "tt1686034",
            "poster": "https://m.media-amazon.com/images/M/MV5BMWJkMWEyMDUtZTkzZS00ZDc5LTg0ZjgtMzViMTljZDUzY2MxXkEyXkFqcGdeQXVyMjAyOTI2MDg@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2021-12-15"
        },
        {
            "title": "Another Round",
            "img": "https://occ-0-2416-185.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABUBtQp9W84Ampp5159BMIZkCy96UM6knce9-RCQPlRsWhOVcP9eCEK75H0skIMKTAkhMDF2790Y3SYwiqVSWgL1zRA.jpg?r=715",
            "title_type": "movie",
            "netflix_id": 81450757,
            "synopsis": "Four stagnant high school teachers decide to test out a theory that maintaining a constant level of intoxication will improve their overall lives.",
            "rating": "0",
            "year": "2020",
            "runtime": "6977",
            "imdb_id": "tt0228018",
            "poster": "0",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2021-08-12"
        },
        {
            "title": "Whitestar",
            "img": "https://occ-0-768-769.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABZdSzh3meYEL6uEDcZr4OhNyNmRBBlGgB90Gb9Gkixfyrw3Rd2a-MQldbRpqUpnQt5U4jtr6uGgAPHwRriTkJ4Ng0A.jpg?r=156",
            "title_type": "movie",
            "netflix_id": 81180977,
            "synopsis": "Following in her late father&#39;s footsteps, gifted teen Megan forms a bond with a special horse and, with love and care, trains him to be a champion.",
            "rating": "0",
            "year": "2020",
            "runtime": "4987",
            "imdb_id": "tt10602694",
            "poster": "https://m.media-amazon.com/images/M/MV5BM2Y0MDEzZTUtZmFhMi00OWQ1LWFhODktZWU2MmEyMGYzOGQxXkEyXkFqcGdeQXVyMjI4Mjg0NTM@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2020-06-14"
        },
        {
            "title": "The Greatest Miracle",
            "img": "https://occ-0-114-116.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABW3iCSvp6U-BEmFgpST8W_AW447bZEwG1hHbp_gaLlOsT53ss3aSCUhX8H8Xg-IkWEVx5dUD6BiFdNEDvCqM1viOfQ.jpg?r=5f8",
            "title_type": "movie",
            "netflix_id": 70297468,
            "synopsis": "This animated feature brings to life the spiritual significance of the Catholic mass, a ritual that has been practiced by the faithful for centuries.",
            "rating": "3.423233",
            "year": "2011",
            "runtime": "4142",
            "imdb_id": "tt1931569",
            "poster": "http://ia.media-imdb.com/images/M/MV5BMTA2NDU2NTY5NTBeQTJeQWpwZ15BbWU3MDg1NzE0MDc@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2015-04-14"
        },
        {
            "title": "Kein Sex ist auch keine Losung",
            "img": "https://occ-0-1348-1347.1.nflxso.net/art/ab471/8cd1511624c305ec52e27f4900deb3e023aab471.jpg",
            "title_type": "movie",
            "netflix_id": 80114942,
            "synopsis": "A serial womanizer&#39;s relationship rules are put to the test when a new employee -- and news of impending bankruptcy -- shakes things up at the office.",
            "rating": "3",
            "year": "2011",
            "runtime": "6582",
            "imdb_id": "tt1825837",
            "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BZmE2NWIxZDktMzE0ZC00MDFiLTkzNmUtZWM1ZjFjYzZmYzM0XkEyXkFqcGdeQXVyNjE4MjY2MDg@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2016-09-01"
        },
        {
            "title": "Junior",
            "img": "http://occ-2-2430-2433.1.nflxso.net/art/fcaa9/aad17c28c16947edee24a29d8310cec8fc9fcaa9.jpg",
            "title_type": "movie",
            "netflix_id": 661883,
            "synopsis": "Their research threatened when they fail to nab a grant, two male fertility doctors test their theory by implanting one of them with an embryo.",
            "rating": "3.0587654",
            "year": "1994",
            "runtime": "6595",
            "imdb_id": "tt0110216",
            "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTYwNjA3MTUxMl5BMl5BanBnXkFtZTcwMDk2MjAyMQ@@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2017-03-01"
        },
        {
            "title": "Backstage",
            "img": "https://occ-0-1490-1489.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABXDtj-bl1s3rhmIhxVvP0CxHaprCq6bNXlba0NMspkBZCoKDn-Xv2ldi3XWK4KVZVhx-HehxU7P_uU3bTEoI_kFxCw.jpg?r=03b",
            "title_type": "movie",
            "netflix_id": 81192809,
            "synopsis": "The members of a talented young dance troupe enter a televised competition where both their moves and friendships are put to the test.",
            "rating": "0",
            "year": "2018",
            "runtime": "5375",
            "imdb_id": "tt7460870",
            "poster": "https://m.media-amazon.com/images/M/MV5BMDcwNWQ0NTUtZmQ1MS00OGRjLThkZjUtM2JkYjQ1NWJhNDU5XkEyXkFqcGdeQXVyMjI3NTk2NDk@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2019-10-08"
        },
        {
            "title": "Johnny Test",
            "img": "https://occ-0-2773-2774.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABaAOT-j0XeemmAft-inPzZqoKQ3PUXTeoidNcoY9LwoJEf-eTk13WNtDpxVJxCzp5qVsBtO54FhEEDBYIY_7sBVNBw.jpg?r=507",
            "title_type": "series",
            "netflix_id": 70155579,
            "synopsis": "Crafty 11-year-old Johnny Test and his genetically modified talking dog go on high-octane adventures to save his family (and the world) from disaster.",
            "rating": "3.4683988",
            "year": "2005",
            "runtime": "0",
            "imdb_id": "tt0454349",
            "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BYzc3OGZjYWQtZGFkMy00YTNlLWE5NDYtMTRkNTNjODc2MjllXkEyXkFqcGdeQXVyNjExODE1MDc@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2015-04-14"
        },
        {
            "title": "Que Leones",
            "img": "https://occ-0-114-116.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABXQ_Wd9Tj--2lCCOlZqrIRRJSFDnpawEm1EPzGD0eWaF4-buP4Px2ByHN1cq_jXnxY7W4MZqwdq4hX8-Pw-97Oeomw.jpg?r=f02",
            "title_type": "movie",
            "netflix_id": 81264171,
            "synopsis": "Eccentric relatives and enticing flirtations cause drama and derail a young couple&#39;s new life in New York City, putting it to the test.",
            "rating": "0",
            "year": "2019",
            "runtime": "5822",
            "imdb_id": "tt9364228",
            "poster": "https://m.media-amazon.com/images/M/MV5BMGRiNjlmMDAtODJkYS00ZTEwLTg0YTAtYzYxZTgyOTc5MzNhXkEyXkFqcGdeQXVyODU4MjAxOQ@@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2020-04-16"
        },
        {
            "title": "Krishna Cottage",
            "img": "https://occ-0-2851-38.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABQuFxlvl240lOdRhO0cc9meGNzmV0Cm77NLa5NThG2_VLXb7w60TMHi7jq3nYXJzvL5r-FYnLQMR6ljcqLyWkL5uTQ.jpg?r=752",
            "title_type": "movie",
            "netflix_id": 70025612,
            "synopsis": "True love is put to the test when another woman comes between a pair of star-crossed young lovers in this thriller.",
            "rating": "2.3707864",
            "year": "2004",
            "runtime": "7438",
            "imdb_id": "tt0408976",
            "poster": "http://ia.media-imdb.com/images/M/MV5BYzZiYjkzODAtNmE0OS00ZTNkLWI0NjYtMTgzYzcxZWRmNWIxXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2016-01-06"
        },
        {
            "title": "The Cave",
            "img": "https://occ-0-2616-2773.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABaM-xTgBmzbEak-K3YP-_nAWd5wM10EHJKN1E1p0gj8GXH4SCv5ut_C6B3PqZaP--hW-f7DPaH2RUYQWqpe7dbB0XA.jpg?r=26d",
            "title_type": "movie",
            "netflix_id": 81367049,
            "synopsis": "Residents of a poverty-stricken neighborhood in Cairo, struggling to make ends meet, are forced into situations that test their ethics and friendships.",
            "rating": "0",
            "year": "2019",
            "runtime": "5756",
            "imdb_id": "tt0402901",
            "poster": "https://m.media-amazon.com/images/M/MV5BMTI4MTQ1NjQ2Ml5BMl5BanBnXkFtZTcwNTkzMTMzMQ@@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2021-05-16"
        },
        {
            "title": "Johnny Test&#39;s Ultimate Meatloaf Quest",
            "img": "https://occ-0-471-2567.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABfLnkc3etolc0SGZPdEyc-0gNhRaGjgWnflmfTFrdmif0h5UsHHIQMAiCQy4XU8hLeeH53w2h7LF95lg1xBw80y2OcJR-LtxK-KqppszTa5bUy6BLwJz6z8sKqIX2uXMADJJIeSrPOJD9QeuUT7XjnHc-lw-Hcv5x7GU1tCKt2pNVdEfrB0uLK7xVBv7UEbK5w6WX77WXSVaqukfw3moGeA.jpg?r=e2c",
            "title_type": "movie",
            "netflix_id": 81287545,
            "synopsis": "Join Johnny and Dukey on an epic interactive quest to find the perfect meatloaf — and save themselves from eating Dad&#39;s gross \"garbage loaf\" for dinner.",
            "rating": "0",
            "year": "2021",
            "runtime": "4213",
            "imdb_id": "tt0454349",
            "poster": "https://m.media-amazon.com/images/M/MV5BZDVhZWVkNTUtMTE1OC00YmViLWJlMzYtNTQwYmI3MmQ3OGYzXkEyXkFqcGdeQXVyODk1MjAxNzQ@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2021-11-16"
        },
        {
            "title": "Johnny Test",
            "img": "https://occ-0-2851-1432.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABfrVpkcnM4XPIdE7E2UEdQxVW2NDHncs54zhDpxpAsxFk27mZO9twucBi6MhcssG7hMyGgY6SL2H7n_b8uZNI86KjNikVg8IhWyNvjyD-Fj6T2kTYEQqtgREfhQ.jpg?r=307",
            "title_type": "series",
            "netflix_id": 81193032,
            "synopsis": "How much trouble could one imaginative boy, his faithful dog and two science-loving sisters possibly get into? Hmm, that sounds like a challenge!",
            "rating": "0",
            "year": "2021",
            "runtime": "0",
            "imdb_id": "tt0454349",
            "poster": "https://m.media-amazon.com/images/M/MV5BZDVhZWVkNTUtMTE1OC00YmViLWJlMzYtNTQwYmI3MmQ3OGYzXkEyXkFqcGdeQXVyODk1MjAxNzQ@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2021-07-17"
        },
        {
            "title": "Baaghi",
            "img": "https://occ-0-2717-360.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABWf-Kk06TEuquv4vUKcHjN8CB2KjPTbDLqfMD2NW13EuTL0-2QbjLyP1owNaxhjKkXptJUCQEQFuDTofFBGzxaHLqQ.jpg?r=b2a",
            "title_type": "movie",
            "netflix_id": 80104648,
            "synopsis": "A martial artist faces his biggest test when he has to travel to Bangkok to rescue the woman he loves from the clutches of his romantic rival.",
            "rating": "0",
            "year": "2016",
            "runtime": "7627",
            "imdb_id": "tt4864932",
            "poster": "https://m.media-amazon.com/images/M/MV5BMDlhYzBmYjgtYzkyMC00MDUwLTkwNzgtYzk4Yjc5ZTU1ODI3XkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2018-08-04"
        },
        {
            "title": "Parterapi",
            "img": "https://occ-0-38-1501.1.nflxso.net/art/4ba31/16ec8d7de78491483d3dbc902bf2612ac684ba31.jpg",
            "title_type": "movie",
            "netflix_id": 70295569,
            "synopsis": "Anders and Puk finally have their own house. But the remodeling is putting their relationship to the test and their counselor is no help at all.",
            "rating": "3.2247646",
            "year": "2010",
            "runtime": "5900",
            "imdb_id": "tt1425624",
            "poster": "http://ia.media-imdb.com/images/M/MV5BMTc3ODY3ODQwN15BMl5BanBnXkFtZTcwNzg1OTk5OA@@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2015-04-14"
        },
        {
            "title": "The Sweetest Thing",
            "img": "https://occ-0-2851-38.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABTBtwpvcXO7lD7CU9gFJfHcQWySR39cptNQnMMvNkwtrlrU14_mE2VSQdqFY92Jpo3TWnx54OBfRrXDhtX08cSMcPQ.jpg?r=dac",
            "title_type": "movie",
            "netflix_id": 60022057,
            "synopsis": "After a brief nightclub encounter with a handsome real-estate agent, a party girl and her best friends embark on a wild road trip to track him down.",
            "rating": "3.5128856",
            "year": "2002",
            "runtime": "5325",
            "imdb_id": "tt0253867",
            "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BNDIyZTkwOGEtYTFlNC00MTU4LWIyNGItYjBlYmFhNDRmYzcwXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2015-04-14"
        },
        {
            "title": "Divorces!",
            "img": "https://occ-0-3607-38.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABWch4RZSfPpg5j6ael6DJfWlp2bxl37jUz2aKA8DPLuiklGvAMQ7kyagTij-iASsp4ggYj_75YyOzlc6ubcTdHfwOQ.jpg?r=5cc",
            "title_type": "movie",
            "netflix_id": 70207975,
            "synopsis": "A husband-and-wife team of divorce lawyers is known for advocating amicable separations, but they&#39;re put to the test when their own marriage crumbles.",
            "rating": "0",
            "year": "2009",
            "runtime": "5978",
            "imdb_id": "tt1520863",
            "poster": "https://m.media-amazon.com/images/M/MV5BZjk4ZThlZjAtOWY4NS00NmIyLWE0MzItOWMxMWUyZDNkOWRmXkEyXkFqcGdeQXVyNzEyMDU1MzU@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2021-08-25"
        },
        {
            "title": "Out of Many, One",
            "img": "https://occ-0-2851-38.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABZIeOpbBQqwe98NU_FDYVjuiFvRwUwZnjvXBoYUwT6c9b-BjegqQe3jrvmdqN4f5ianb-9LI4_3Opj-sjZQIKQ1eywc0BGBBEnVW-48NueaJFlGezncOjgR0l3I.jpg?r=eb4",
            "title_type": "movie",
            "netflix_id": 81010212,
            "synopsis": "In this documentary short, a diverse group of men and women discuss their personal journeys as they prepare for the U.S. citizenship test.",
            "rating": "0",
            "year": "2018",
            "runtime": "2084",
            "imdb_id": "tt9283302",
            "poster": "https://m.media-amazon.com/images/M/MV5BMWVhNTJmODUtZmU5MC00OTdjLTkwNGUtNWJkYjYyNDEyMmUwXkEyXkFqcGdeQXVyNDg4NjY5OTQ@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2018-12-12"
        },
        {
            "title": "Legiony",
            "img": "https://occ-0-4587-1432.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABcWWNC7eIp_Ibo-6wFQnbQ0bX82ts4zACiAkOeyBvjJ0MpuOLd1Z6dO60jOCSW89Ij4XXaYdTWC0p3KB94c5FLDYlw.jpg?r=2db",
            "title_type": "movie",
            "netflix_id": 81278719,
            "synopsis": "As a Polish militia battles for independence from Russian rule in the 1910s, a star-crossed romance puts loyalties to the test. Inspired by true events.",
            "rating": "0",
            "year": "2019",
            "runtime": "8383",
            "imdb_id": "tt9546624",
            "poster": "https://m.media-amazon.com/images/M/MV5BOTMxNjNjMGEtYmNkNi00YWRiLTgzN2ItNTgzMmZhYjdlMzkzXkEyXkFqcGdeQXVyMTEwMTY3NDI@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2020-12-12"
        },
        {
            "title": "The Bridge Curse",
            "img": "https://occ-0-2705-2706.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABXT8raRxD_8ZzJfJuj4nnCRg_hJOTZmTjXOcHNrCH0rj_h7Z1w_UR6on6lAN9GBSMtcL-3_JyJpDFhI4cBvwiM2ZKg.jpg?r=405",
            "title_type": "movie",
            "netflix_id": 81224632,
            "synopsis": "A group of university students decides to test an urban legend about the ghost of a female student that haunts a campus bridge.",
            "rating": "0",
            "year": "2020",
            "runtime": "5268",
            "imdb_id": "tt11242242",
            "poster": "https://m.media-amazon.com/images/M/MV5BZjk2MzQ0ZTMtMThlNi00MmQ1LWJmNWEtN2I0MDlhMGJkMjBiXkEyXkFqcGdeQXVyNjgwNTk4Mg@@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2020-08-27"
        },
        {
            "title": "Love of My Life",
            "img": "https://occ-0-2740-64.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABfIr_KXEB3vqqC0sVqxOIV42Tr9JVXw2i85HJK2rp51S3EeHpI85lTRv4-Hn4tc9nf8nZfLGC2nprvnUtxfIwmFtvg.jpg?r=78c",
            "title_type": "series",
            "netflix_id": 81437983,
            "synopsis": "An architect from an affluent family tries to build a life with a business owner, but pain and tragedy soon put their love and happiness to the test.",
            "rating": "0",
            "year": "2020",
            "runtime": "0",
            "imdb_id": "tt4994564",
            "poster": "https://m.media-amazon.com/images/M/MV5BZDRhOGMyZmUtZDYzMi00OTY0LTkyNjQtYjk4ZDY4OGFiODNjL2ltYWdlXkEyXkFqcGdeQXVyMTcxMTgyMTE@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2021-05-28"
        },
        {
            "title": "D.E.B.S.",
            "img": "https://occ-0-2773-2774.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABd_ZYZEkbawHajZkcErZOneaWZTPFVMP-h0GJCPBGDENrP_4n6L4kqyf4K789NpknTpJsDRhqtUwDCusDrHxpm6ywQ.jpg?r=f4a",
            "title_type": "movie",
            "netflix_id": 60034795,
            "synopsis": "When four girls ace an SAT test that secretly measures a teen&#39;s potential for espionage, they&#39;re recruited for the elite paramilitary group D.E.B.S.",
            "rating": "0",
            "year": "2004",
            "runtime": "5509",
            "imdb_id": "tt0367631",
            "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMjA0OTU5ODgyOF5BMl5BanBnXkFtZTcwODczNDgyMQ@@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2017-04-20"
        },
        {
            "title": "Medicinen",
            "img": "https://occ-0-1926-41.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAABfmjBreNm3RbWLgn90rwPs7k9jgEixpY_BsXOLEM7Fb34A3gfKLFoYOmN2sFnRkD1hoEp_pkAwtxffyT9emVixFibA.jpg?r=320",
            "title_type": "movie",
            "netflix_id": 80202918,
            "synopsis": "When her husband leaves her for a younger woman, a cash-strapped reporter volunteers to be a pharmaceutical test subject, with unexpected results.",
            "rating": "0",
            "year": "2014",
            "runtime": "6880",
            "imdb_id": "tt3117184",
            "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BZTM1NWRmMDktYWRhOS00MDA3LWExZjEtOTJlNWIyZDFkMTY2XkEyXkFqcGdeQXVyMTQzMjU1NjE@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2017-12-15"
        },
        {
            "title": "Ninja",
            "img": "https://occ-0-2042-299.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABXYemeVWH4-XeHv2SHTRVXourHiJnHJqGZUB7FOKQ_s4N0X68sAB8E9_umJDrXKauvS7bu57ZB3FL2b9Btg1d2b9cw.jpg?r=abe",
            "title_type": "movie",
            "netflix_id": 70119827,
            "synopsis": "An American studying ninjutsu in Japan finds his training put to the test when his sensei summons him to return to New York for a dangerous mission.",
            "rating": "3.2376056",
            "year": "2009",
            "runtime": "5176",
            "imdb_id": "tt1182921",
            "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTM3N2JkZDEtOTYwNy00NmNhLWI0YTktMTQwOTliYzU0NTc2L2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2015-04-14"
        },
        {
            "title": "Green Lantern",
            "img": "https://occ-0-2851-38.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABdI1-smNC-ZvCTEpeAPo9pq8ikMj7QEN9Z_VR1hvk8UvkqHC6UMpLGAYKa4eiZnmD_sOke9hdLNVV_8Js6S-bBTs-A.jpg?r=a46",
            "title_type": "movie",
            "netflix_id": 70143807,
            "synopsis": "A talented test pilot is chosen by alien warriors to become their representative on Earth and uses his new powers as the Green Lantern.",
            "rating": "3.441141",
            "year": "2011",
            "runtime": "6849",
            "imdb_id": "tt1133985",
            "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTMyMTg3OTM5Ml5BMl5BanBnXkFtZTcwNzczMjEyNQ@@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2015-04-14"
        },
        {
            "title": "The Cloverfield Paradox",
            "img": "https://occ-0-2851-38.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABfoa2pD9DDRY6cBKWI0xslAxLvklePxjDF6zk5RCM-O4CqQuIfsulNtjtUyVzI45wWlwx1VIyQvPLWPHBp-fNVJt6OjQqrRL7FOit5EO6NjeADX6E1WeUNVmEXk.jpg?r=28c",
            "title_type": "movie",
            "netflix_id": 80134431,
            "synopsis": "Orbiting above a planet on the brink of war, scientists test a device to solve an energy crisis and end up face-to-face with a dark alternate reality.",
            "rating": "0",
            "year": "2018",
            "runtime": "6146",
            "imdb_id": "tt2548396",
            "poster": "N/A",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2018-02-05"
        },
        {
            "title": "Scoob",
            "img": "https://occ-0-1373-2568.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABdB5wH73l8eCvyaDextur4dbrkZkCPGNKUuHrGTNFp3mhL1PvUyOpn6zhfgbNqAymlTyM5aL4ggo9lxarRSfo9H6KQ.jpg?r=18a",
            "title_type": "movie",
            "netflix_id": 81198897,
            "synopsis": "The bond between Shaggy, Scooby and the Mystery Inc. crew is put to the test when a villain nabs the hungry hound to unlock a mighty destiny.",
            "rating": "0",
            "year": "2020",
            "runtime": "5623",
            "imdb_id": "tt3152592",
            "poster": "https://m.media-amazon.com/images/M/MV5BZTJmODM0MDQtMTRjYy00YWZjLThjODItMzQ5N2I2NDBjYzA1XkEyXkFqcGdeQXVyMDA4NzMyOA@@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2021-01-01"
        },
        {
            "title": "Nakee",
            "img": "https://occ-0-3466-3467.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABUy9wq9P03uv3izhz3vQ7W4hn0TjzlSNrmMbHfA1hddXiwdZ44ayWHTdeOU4SD93FbWVpnFCWFTbsmaTaHnvTQjI6g.jpg?r=df2",
            "title_type": "series",
            "netflix_id": 81343084,
            "synopsis": "A mysterious girl with superpowers takes on sinister forces through a curse connected to an ancient goddess as obstacles test her and the man she loves.",
            "rating": "0",
            "year": "2016",
            "runtime": "0",
            "imdb_id": "tt9169974",
            "poster": "https://m.media-amazon.com/images/M/MV5BNjFiOTllN2YtYzVlZS00ZGNhLWJmOGItMmJlZDhjYmQ0ZjE3XkEyXkFqcGdeQXVyNzg4NDEyNDk@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2020-11-29"
        },
        {
            "title": "Outback Lockdown",
            "img": "https://occ-0-1705-299.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABWDaO1movk2cBCde7sddqP56_Sd3P0WipENOWUu6f05lM9-u3WE0BSbP8mUZbGBdHsdezlMV-h6hcCjuWDEvdBWyaA.jpg?r=249",
            "title_type": "series",
            "netflix_id": 81464384,
            "synopsis": "Survival expert Ky Furneaux and chef Calem O’Grady test their skills — and their new relationship — living off the land in Australia&#39;s Outback in 2020.",
            "rating": "0",
            "year": "2020",
            "runtime": "0",
            "imdb_id": "tt12724210",
            "poster": "https://m.media-amazon.com/images/M/MV5BMTA0MWZkYjktYjg3Yi00ZTQxLWJlYzctZGFiMDIwNmMxZDdiXkEyXkFqcGdeQXVyMTAwMzM3NDI3._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2021-07-10"
        },
        {
            "title": "TAU",
            "img": "https://occ-0-2773-2774.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABeLx90hGhSPNIcgwkLaw__SsUvdP5qeAH_Ks0aEupIh6ZH2We8mT3ZZpHmspgJQ6ZPYC4bl5zlAbKgazT1h70hoBbdo7ap8PnLI9S-rfGllikLtRrcY07y1Rjx8.jpg?r=32a",
            "title_type": "movie",
            "netflix_id": 80217569,
            "synopsis": "Kidnapped by an inventor who uses her as a test subject to perfect his robotic AI, a street-smart young woman tries to escape her high-tech prison.",
            "rating": "0",
            "year": "2018",
            "runtime": "5860",
            "imdb_id": "tt4357394",
            "poster": "https://m.media-amazon.com/images/M/MV5BNmYzYWNhYWQtNjg0MS00NWU5LTgyZGUtYzViNjgwY2NjY2YwXkEyXkFqcGdeQXVyNjYzMzU4OTg@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2018-06-29"
        },
        {
            "title": "Whispering Corridors 3: Wishing Stairs",
            "img": "https://occ-0-1007-1360.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABUJJjNuVNRvgCWnW2htKW-hlTLdOXmNQkhopPriyZGb28951SPjyZD1vl8YP0TbSWCKcocJbXtf_ZjugGk154tsUfA.jpg?r=88a",
            "title_type": "movie",
            "netflix_id": 70034737,
            "synopsis": "Students at a girls&#39; boarding school test the legend of a mysterious staircase that is said to grant wishes once a secret step is revealed.",
            "rating": "0",
            "year": "2003",
            "runtime": "6032",
            "imdb_id": "tt0370082",
            "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BNjczNWE0ZDItM2YwZi00ZDM0LWI1NTQtOTczZWU3YzlmOWIwXkEyXkFqcGdeQXVyNjQ2MjQ5NzM@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2018-10-01"
        },
        {
            "title": "Osmosis",
            "img": "https://occ-0-2851-38.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABZPhpBdNb7unQ6kx2OjrRbmoVLAFH8VKl-BTBoLS3vyZ5mXpb6vt-CbFf0FfShaZBzMdIVBq-_MYGCUPv2Jf7eOJ0hTlkN6uBJa9Szfjdi0VGfsNWC6T25a8Pgs.jpg?r=817",
            "title_type": "series",
            "netflix_id": 80189898,
            "synopsis": "In near-future Paris, two brilliant siblings unveil a high-tech implant designed to pair up soul mates. But the beta test yields unwelcome surprises.",
            "rating": "0",
            "year": "2019",
            "runtime": "0",
            "imdb_id": "tt7043380",
            "poster": "N/A",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2019-03-29"
        },
        {
            "title": "Something Borrowed",
            "img": "https://occ-0-2773-2774.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABXy0SNTSzFPC6P-8818ZuZhlrIiA-B3_5On7OKoDlZobh8CLEwlL2ZWdNe2KNdFsswzFsJBRbWDztGFRU6l7nN47xA.jpg?r=040",
            "title_type": "movie",
            "netflix_id": 70167066,
            "synopsis": "In this genial romantic comedy, a lifelong friendship is put to the test when a successful single lawyer ends up in bed with her best friend&#39;s fiancé.",
            "rating": "3.7088106",
            "year": "2011",
            "runtime": "6763",
            "imdb_id": "tt0491152",
            "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BNzczNzMzODk0Nl5BMl5BanBnXkFtZTcwMjgwMjI0NA@@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2015-04-14"
        },
        {
            "title": "The Boss Baby: Get That Baby!",
            "img": "https://occ-0-2851-1432.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABYijeVNKcrzBJLVL7L8fii1OYT-7pwnAPqU15o2idBgrBhRZcRnBep5bTw673JnBt7TWTDuX2FZ1QZiGxnLKvbiKMazRjggML4jLEiAbEtoLt320sm0ZhwuNXm5jdJhZzWmrDoU78za-KW7VTKn5C8hO4zOT.jpg?r=e5e",
            "title_type": "movie",
            "netflix_id": 81054409,
            "synopsis": "Think you&#39;ve got what it takes to be the boss? This interactive special puts your skills to the test and matches you up with one of 16 jobs at Baby Corp.",
            "rating": "0",
            "year": "2020",
            "runtime": "6874",
            "imdb_id": "tt12917148",
            "poster": "https://m.media-amazon.com/images/M/MV5BMjUwNTkzNTktMDkzYi00OGYxLThjZmUtMDFmOGRiYmQwMmE4XkEyXkFqcGdeQXVyMjUxMTY3ODM@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2020-09-01"
        },
        {
            "title": "Shortest Day",
            "img": "https://occ-0-4039-2774.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABUxXMwtOGawr5aSjSvk6-v39kWHvxjOuMl3B2eGCOIuAL9WzXraf46PRckQI6jtk_UGEVMYCxdor-NUQmnoFfSqE2A.jpg?r=f74",
            "title_type": "movie",
            "netflix_id": 81411211,
            "synopsis": "A Sicilian street vendor and his bumbling relative join the Italian army and fight on the front lines of World War I.",
            "rating": "0",
            "year": "1963",
            "runtime": "5438",
            "imdb_id": "tt0056018",
            "poster": "https://m.media-amazon.com/images/M/MV5BNjEyZTYxOGQtNjI1MC00MzBjLTg1N2ItOGE2OGJmOGZkZWZhXkEyXkFqcGdeQXVyMzYyNjE5NDY@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2021-04-28"
        },
        {
            "title": "Mercury Rising",
            "img": "http://occ-0-531-2705.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABU1R_eBpHtOC-oGliuiIK2fqiqJNB9-AbGW2eaxwhotLWDQL5I43lItumGznPoEnCO4LYOx9Aj1GRm5viHetQ23GGg.jpg?r=472",
            "title_type": "movie",
            "netflix_id": 17687517,
            "synopsis": "An autistic 9-year-old boy cracks the U.S. government&#39;s top-secret code when an unapproved test matrix gets published in a crossword magazine.",
            "rating": "3.6265864",
            "year": "1998",
            "runtime": "6681",
            "imdb_id": "tt0120749",
            "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BODA2NmY4NDEtNjk1Yi00NmI1LTgwMjEtYWZmMjRmMDUyMTlkL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2016-10-01"
        },
        {
            "title": "About Last Night",
            "img": "https://occ-0-2851-38.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABflThHHykk0YaLljfxtdpN7lbV4ZuXL2YdpoHX5ifoeeS0glMRVtR18DplPqWiRsaEZOzU99A0eLxG4RkIdM1H3qkw.jpg?r=7fd",
            "title_type": "movie",
            "netflix_id": 70291097,
            "synopsis": "After a couple&#39;s flirtation quickly moves from the bar to the bedroom, they test if their physical chemistry is enough to carry a real relationship.",
            "rating": "3.2258453",
            "year": "2014",
            "runtime": "6013",
            "imdb_id": "tt1826590",
            "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTk3OTc4NDMzNF5BMl5BanBnXkFtZTgwNjQ2NzY3MDE@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2016-02-20"
        },
        {
            "title": "Sonsuz Aşk",
            "img": "https://occ-0-2773-2774.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAAAVqFDEbUi0Z9yzSdVpI2Nt-cKcRnT34ARa9C9gX6MX4FIgxA06F2fQNRkDCgTSpuXbsuF2jXmEYGWiQGKNsZ8LGeMA.jpg?r=f1c",
            "title_type": "movie",
            "netflix_id": 81043525,
            "synopsis": "Sparks fly when a humble housekeeper crosses paths with a wealthy surgeon, but their different lifestyles put their relationship to the test.",
            "rating": "0",
            "year": "2017",
            "runtime": "6859",
            "imdb_id": "tt6690234",
            "poster": "https://m.media-amazon.com/images/M/MV5BYjJmZjM2ZmQtMzRkZC00NjBlLThhNGYtNGJiYzRjOGNiYTE0XkEyXkFqcGdeQXVyNTk2MjQ5MzE@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2019-04-05"
        },
        {
            "title": "Love Is Love",
            "img": "https://occ-0-64-325.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABVitSYugYngs57Cr72PWpE1DrPKNcDhsJVG-LJ4gsn4KkIsWPer-xl8rAAn3IAJa4UzOE2kG8rPz8mW6D8MbeaLsWA.jpg?r=1d7",
            "title_type": "movie",
            "netflix_id": 81038417,
            "synopsis": "Defying family expectations, a pair of childhood sweethearts wed and move to the big city, where work life and temptations test their relationship.",
            "rating": "0",
            "year": "1990",
            "runtime": "5756",
            "imdb_id": "tt0100902",
            "poster": "https://m.media-amazon.com/images/M/MV5BMTIyMjkwODU3NF5BMl5BanBnXkFtZTcwMDczNjEyMQ@@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2018-12-27"
        },
        {
            "title": "Chloe",
            "img": "https://occ-0-768-769.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABRKoR7F3l3ml8Zig6YP33SETBwEyiw50bg14v2a9IZMFdW4-Eo-_JXmgugcmWErzvu95r7LgDfzikDqzKVSnKbJxiA.jpg?r=98d",
            "title_type": "movie",
            "netflix_id": 70124183,
            "synopsis": "Suspecting her husband of infidelity, Catherine hires sexy Chloe to test his faithfulness. Soon, the relationships between all three intensify.",
            "rating": "3.224501",
            "year": "2009",
            "runtime": "5767",
            "imdb_id": "tt1352824",
            "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTczMzExNTkyMV5BMl5BanBnXkFtZTcwODUyMzAyMw@@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2015-04-14"
        },
        {
            "title": "The Assassin",
            "img": "https://occ-0-1168-299.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABfOAJVeyiYU2jsrEtxN8h_WnUh11KKln8VmOLD9w4pKlk5ZSJH9fmgrgN-PIqhfN3-fZhNaYm8FPGY7VMAJRl0BFFA.jpg?r=c43",
            "title_type": "movie",
            "netflix_id": 80057360,
            "synopsis": "A young woman who was kidnapped as a child and trained as an assassin faces a test of her loyalty when she is ordered to kill her cousin.",
            "rating": "2.527099",
            "year": "2015",
            "runtime": "6326",
            "imdb_id": "tt3508840",
            "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BNTczMTk3MjMyOV5BMl5BanBnXkFtZTgwMjA2Mjk4NjE@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2016-03-26"
        },
        {
            "title": "The Perfect Picture: Ten Years Later",
            "img": "https://occ-0-2851-1432.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABS_OwXTu2CeRLWWyIMrijQ2A1jcUIy1qEzlvAgLwIOkpnnA7z5nUkwoA6ilixzLu08-Cg55sevQcsk51G8UZCHEjSA.jpg?r=1a0",
            "title_type": "movie",
            "netflix_id": 81281633,
            "synopsis": "From flawed husbands to shaky finances, new complications test a close circle of friends who must lean on each other in a new decade of their lives.",
            "rating": "0",
            "year": "2019",
            "runtime": "8867",
            "imdb_id": "tt12058774",
            "poster": "https://m.media-amazon.com/images/M/MV5BNmQ3YWUwNzItN2UxZi00NzljLTkzOWItNjJjZmZjYmU1NDZmXkEyXkFqcGdeQXVyMjI4NDIyNDY@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2020-07-03"
        },
        {
            "title": "A la mala",
            "img": "http://occ-2-2301-185.1.nflxso.net/art/5ba19/3b6e516a422060a8d4d62ede3f736eb79bb5ba19.jpg",
            "title_type": "movie",
            "netflix_id": 80035466,
            "synopsis": "When an aspiring actress agrees to test the fidelity of her best friend&#39;s beau, she finds a way to profit from her talent, until she falls in love.",
            "rating": "2.9200168",
            "year": "2015",
            "runtime": "6337",
            "imdb_id": "tt4357170",
            "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BNjEzODA5OTU3Nl5BMl5BanBnXkFtZTgwMzcyODAxNDE@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2015-12-22"
        },
        {
            "title": "Ask the Doctor",
            "img": "https://occ-0-2851-38.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABTx2HDmquVeK8RH_HSvdGmkvaU4iSe2Bxwv_-Gemkrvwi0NQHacNbBC3s8te6LqXGmWm3HviMT_1d6utrZp0aLZTd3Q22ZuVWZcr2YhxYmQC-AOZiQOZAOoEitI.jpg?r=97f",
            "title_type": "series",
            "netflix_id": 81003997,
            "synopsis": "From allergies to diet to sleep, three friendly doctors share expert advice, bust medical myths and test the latest treatments.",
            "rating": "0",
            "year": "2017",
            "runtime": "0",
            "imdb_id": "tt7188736",
            "poster": "https://ia.media-imdb.com/images/M/MV5BYTAyOWI5ZDMtNTQ2NC00MDc5LTg1M2MtZmQxOTc4Y2M4MWQwXkEyXkFqcGdeQXVyNTE4NTk4Njg@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2018-10-19"
        },
        {
            "title": "Wheelman",
            "img": "https://occ-0-2773-2774.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABdmRAHTKSgXNEzhfKNGmEqhkB1CX2b2FD9Tybgb3CoH5ZOciqwyyic8IrtceYniAxuULDfEimHbujnJcaKAktDjY9ViSVXXPZtABVf1hu9Xy3yZq_moueq8ry5Q.jpg?r=4d6",
            "title_type": "movie",
            "netflix_id": 80113669,
            "synopsis": "The getaway driver in a botched robbery puts his skills and smarts to the test when he receives shocking orders from an unknown caller.",
            "rating": "0",
            "year": "2017",
            "runtime": "4947",
            "imdb_id": "tt5723286",
            "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMjA3NjA0MzE1N15BMl5BanBnXkFtZTgwNjAzNzQ0MzI@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2017-10-20"
        },
        {
            "title": "A Love Story",
            "img": "https://occ-0-2851-38.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABc30fsS9zuTcFH2BuK3SEuf0GNEx3mhyDzBbRA2FmnoGRXQF6AC2eVoCKI8cQQapDnUmBTb4_zCHzFJK3ck0siA_Uw.jpg?r=204",
            "title_type": "movie",
            "netflix_id": 70090072,
            "synopsis": "Self-made millionaire Ian thinks he&#39;s found happiness when he marries caring Joanna, but his love is put to the test when he meets stewardess Karyn.",
            "rating": "0",
            "year": "2007",
            "runtime": "7043",
            "imdb_id": "tt0990433",
            "poster": "https://ia.media-imdb.com/images/M/MV5BZWJhZGQ0ZmYtNmRmYi00YWNhLWJjNjQtMzVjNDc1MDFmMjFiXkEyXkFqcGdeQXVyNTI5NjIyMw@@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2019-03-14"
        },
        {
            "title": "The Brothers",
            "img": "https://occ-0-2851-38.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABdbIl6b8KszZuNCLiAO1frtCfDhomt_p3zXKCunBVdTNvvYEL8WcCnLAjGtxfaUmBkiinxaT4mnLoOk9806BTXYs5w.jpg?r=b2f",
            "title_type": "movie",
            "netflix_id": 60020762,
            "synopsis": "Four close-knit friends test the limits of honesty and commitment as they barhop, climb the career ladder and incessantly fall in and out of love.",
            "rating": "3.7287595",
            "year": "2001",
            "runtime": "6135",
            "imdb_id": "tt0250274",
            "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMjA3OTM2NDM3NV5BMl5BanBnXkFtZTYwNjA3NjU3._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2015-04-14"
        },
        {
            "title": "A Guy & A Girl",
            "img": "https://occ-0-2774-2773.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABSYMkvJ-neOFqu7vMHbwsEuR1RttrFwjJ55S71DkCKNlFLqR6sRvB5DaAu3OYk9xEXeoRfGCj39kzhUGfsmXyxNZLw.jpg?r=370",
            "title_type": "movie",
            "netflix_id": 81323769,
            "synopsis": "An adolescent crush evolves into a complicated romance for Shahed and Sameh, whose differences constantly test their relationship.",
            "rating": "0",
            "year": "2010",
            "runtime": "6450",
            "imdb_id": "tt0251127",
            "poster": "https://m.media-amazon.com/images/M/MV5BMjE4NTA1NzExN15BMl5BanBnXkFtZTYwNjc3MjM3._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2020-11-13"
        },
        {
            "title": "Irreplaceable",
            "img": "https://occ-0-3876-64.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABZjZAswMCdATzzPd2oRbuf2tgYsBS2ttRUxe1-TUsfwmKhxyNCEcdxC8vaEV5LM468kgCcIY4g51QuUTsXa6-SJY5w.jpg?r=709",
            "title_type": "series",
            "netflix_id": 81499529,
            "synopsis": "After their son is abducted, an estranged couple is forced to come together on a perilous journey to save their child, putting their love to the test.",
            "rating": "0",
            "year": "2020",
            "runtime": "0",
            "imdb_id": "tt5078326",
            "poster": "https://m.media-amazon.com/images/M/MV5BN2Y0MzM0ODgtMzY0Mi00ZTBjLThhYjItYzU4ODI3NDg1NzdlXkEyXkFqcGdeQXVyNjU3MDQ1Njg@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2021-12-24"
        },
        {
            "title": "Woodlawn",
            "img": "https://occ-0-114-116.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABfmkdnN4ms3j_v0zfshk8YWN40UVYcCVpx0rvXco24_4TxetS-1huwy0ElZnI4Z6zGDWYDMmk46khabZp-nS74y35g.jpg?r=4e6",
            "title_type": "movie",
            "netflix_id": 80049950,
            "synopsis": "In 1970s Alabama, racial divisions test the talent, faith and mettle of black high school football star Tony Nathan, both on and off the gridiron.",
            "rating": "3.9602313",
            "year": "2015",
            "runtime": "7407",
            "imdb_id": "tt4183692",
            "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTA0ODM5MTM5MTleQTJeQWpwZ15BbWU4MDAwNzk1NDYx._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2016-04-19"
        },
        {
            "title": "Eurovision Song Contest: The Story of Fire Saga",
            "img": "https://occ-0-768-769.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABabHtIKTTULb_W9gvEdyr39xBJdRRqHUB97jv9DXGL2HuIwajcr89LkGhUO26dN9PeBTAx038ivFj4R9jl50DAZIuXseqvm90j4C5WlNvAnzUc8t159OdrKOB84.jpg?r=e7f",
            "title_type": "movie",
            "netflix_id": 80244088,
            "synopsis": "Two small-town singers chase their pop star dreams at a global music competition, where high stakes, scheming rivals and onstage mishaps test their bond.",
            "rating": "0",
            "year": "2020",
            "runtime": "7414",
            "imdb_id": "tt8580274",
            "poster": "https://m.media-amazon.com/images/M/MV5BYzRjYzA5NTQtOTE3MC00OTYzLWEzODItMzQxYWE1NDJkMDA0XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2020-06-26"
        },
        {
            "title": "Sexy Beasts",
            "img": "https://occ-0-4039-1500.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABT0dvmgPKea7oKo-m9pd19tRmEEqjKqwMHWWvEXlRZrHzjkhURbd7zkUTajc3LT06Cbd2n1Zb9sq94UkiTHm3ZMLrJB4-LidwGTZTraoqsEJfeXLBZ_m8OLnSRQ.jpg?r=512",
            "title_type": "series",
            "netflix_id": 81298845,
            "synopsis": "Hoping to say goodbye to superficial dating, real-life singles sport elaborate makeup and prosthetics to put true blind-date chemistry to the test.",
            "rating": "0",
            "year": "2021",
            "runtime": "0",
            "imdb_id": "tt3540274",
            "poster": "https://m.media-amazon.com/images/M/MV5BMzk2Nzg3MDg4OV5BMl5BanBnXkFtZTgwNjc5NDg1NTE@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2021-07-22"
        },
        {
            "title": "The American Bible Challenge",
            "img": "http://occ-0-2218-2794.1.nflxso.net/art/a6502/ce06f7666fd2529ce0a1de83ed5c94991cba6502.jpg",
            "title_type": "series",
            "netflix_id": 80109612,
            "synopsis": "Join host Jeff Foxworthy as contestants test their knowledge of all things biblical, competing to win money for the charities of their choice.",
            "rating": "3.064516",
            "year": "2013",
            "runtime": "0",
            "imdb_id": "tt2246424",
            "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BODY3Yjg5ZTEtZjk5Zi00NTAyLWFiZjktZjY3MGEwMjU1ZmJkXkEyXkFqcGdeQXVyMzU5MTkyMg@@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2016-09-01"
        },
        {
            "title": "The Brightest Roof in the Universe",
            "img": "https://occ-0-3187-3188.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABa_1_2yLbtu4_HX6qlxMk6zTsaou-D0X1btBRid9eW5ZWuy0pXpjvljKzqmEm1lfJfRWA1QJN3mfXYpWEc3xWL_9Rw.jpg?r=30a",
            "title_type": "movie",
            "netflix_id": 81410536,
            "synopsis": "One brief, magical summer, a lonely 14-year-old girl befriends a free-spirited old lady on a rooftop and begins to find her own place in the world.",
            "rating": "0",
            "year": "2020",
            "runtime": "6921",
            "imdb_id": "tt12490780",
            "poster": "https://m.media-amazon.com/images/M/MV5BYmM4ODI3MTEtOGUyMC00OWU0LTliMmMtMWJiNzdmNDlhYjY5XkEyXkFqcGdeQXVyNjE4OTY3NTg@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2021-07-04"
        },
        {
            "title": "The Testament of Sister New Devil",
            "img": "https://occ-0-1007-1360.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABZWlyqxaL8af_l9xjH7F8VvJWWkzUKEX7I8WBjH9aWi5aDmbNOLpXSUrjw82aQzQHuVH68C0JEw1NKnOO7gpbH77yg.jpg?r=f26",
            "title_type": "series",
            "netflix_id": 80193356,
            "synopsis": "Basara hails from a clan of heroes, but when his father suddenly remarries, he finds himself living with a family of demons.",
            "rating": "0",
            "year": "2015",
            "runtime": "0",
            "imdb_id": "tt4219258",
            "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BZTZmNmY1MDMtNzM4OC00Nzc5LWE1ZmUtYjNmNDMwMGIyZjg5L2ltYWdlXkEyXkFqcGdeQXVyMzgxODM4NjM@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2017-12-29"
        },
        {
            "title": "Chronicle of a Blood Merchant",
            "img": "https://occ-0-1007-1361.1.nflxso.net/art/ce45e/5e7b09cf8001735dc5615a0a2f6db3f0a5ace45e.jpg",
            "title_type": "movie",
            "netflix_id": 80186643,
            "synopsis": "Not rich but still comfortably settled, a family man finds his life in disarray when a blood test reveals a mismatch between him and one of his sons.",
            "rating": "0",
            "year": "2015",
            "runtime": "7437",
            "imdb_id": "tt3797004",
            "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BZWZlNGFhOTMtMWQwYi00NzFiLWEwYTgtNzkzNDM3ODgwNzlhXkEyXkFqcGdeQXVyNDI3NjcxMDA@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2017-06-09"
        },
        {
            "title": "Diamonds in the Sky",
            "img": "https://occ-0-2851-1432.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABXhuqNcXXfsDPegExcm6r5jNlRi_l-0F7SxXpyAU23a4rmh9B-c4v9k0n5ncFPLMNjQPmZx4W2ncSprBFXXLMcalrg.jpg?r=360",
            "title_type": "movie",
            "netflix_id": 81281635,
            "synopsis": "Three families navigate uncertainty and struggle when cancer affects their lives and presents emotional challenges that test their bonds.",
            "rating": "0",
            "year": "2018",
            "runtime": "6765",
            "imdb_id": "tt2338287",
            "poster": "",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2020-08-07"
        },
        {
            "title": "Heart & Soul",
            "img": "https://occ-0-179-299.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABXr9xBq6jk2yLKg66V7pnxckX1qSbfpk83Zy-p7IFl-RVIk1_lMGf7ZH7n7XXs2Q0sPRofJ6EAoVy6OXomIbooS24Q.jpg?r=01c",
            "title_type": "series",
            "netflix_id": 81324708,
            "synopsis": "At a hospital in Lagos, a doctor yearning for more field experience meets patients with various ailments that test his spiritual and medical beliefs.",
            "rating": "0",
            "year": "2021",
            "runtime": "0",
            "imdb_id": "tt0099429",
            "poster": "https://m.media-amazon.com/images/M/MV5BNzZiZTY0NTMtNTFhMC00OTA1LTg5ZmQtMjYwNThhNDJiOTVkXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2020-11-20"
        },
        {
            "title": "Out of the Furnace",
            "img": "https://occ-0-1490-1489.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABWSW3Oj5pLEn5T9CfB8SvSCpMoYfmNrWJaWdf0Q1cKCSDBa4gmPAcFm68kzLOLkjE5LJaG3Jnef63ONHv1151mMzSg.jpg?r=072",
            "title_type": "movie",
            "netflix_id": 70241419,
            "synopsis": "The brotherly bond between two blue-collar siblings is put to the test when one lands in prison and the other gets mixed up with a crime syndicate.",
            "rating": "3.7066352",
            "year": "2013",
            "runtime": "6968",
            "imdb_id": "tt1206543",
            "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTc2MTQ4MDU4NV5BMl5BanBnXkFtZTgwOTU1ODgzMDE@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2015-04-14"
        },
        {
            "title": "Backstage",
            "img": "https://occ-0-2773-2774.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABUtfT1GgWf6sL7fvlCZlpThoKNjHJLBKBN_UG8JciFtk94FbH3pOs91Fcqbn3gN63_C9csZPfyVBLgMIao6mCaXQ2A.jpg?r=6b9",
            "title_type": "series",
            "netflix_id": 80102200,
            "synopsis": "Teens at an elite school for the arts sing, dance and act their way through performances as they face challenges that test them onstage and off.",
            "rating": "3.4210527",
            "year": "2016",
            "runtime": "0",
            "imdb_id": "tt4916574",
            "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMWUwYzc0NGQtYTQ0ZC00Mjk0LWFhNTEtNDgxZDY5YjFkYjMxXkEyXkFqcGdeQXVyMDkxMzExOA@@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2016-12-15"
        },
        {
            "title": "My Rebound Girl",
            "img": "https://occ-0-1892-64.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABTgwTvZ0gpJrOlZ3H0s3tpOuqxhnqg4_Awe8MOHOAZNNuOA74uWBGxkjTGpX1E4y5cTshItL0sQ4__U4fkEN1_MnCA.jpg?r=486",
            "title_type": "movie",
            "netflix_id": 81365117,
            "synopsis": "A coffee shop proprietor creates firm dating guidelines to avoid further heartbreak, but a new business partner soon puts her rules to the test.",
            "rating": "0",
            "year": "2016",
            "runtime": "6621",
            "imdb_id": "tt6066948",
            "poster": "https://m.media-amazon.com/images/M/MV5BMzVkYjYwZTktZGYwNS00YzVmLWE5ZjAtYTEwMzE4NDBjMzJjXkEyXkFqcGdeQXVyNTI5NjIyMw@@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2021-04-12"
        },
        {
            "title": "Demon King Daimao",
            "img": "https://occ-0-2773-2774.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABY8tGg8_DDczgJaS-Xr24DYSQFXWardIc3xVbI2tja9wjp8e1ig6H5Sug7AydpcI_oppkjlxknRE-MHYgsmlbgqOfw.jpg?r=5e3",
            "title_type": "series",
            "netflix_id": 70201871,
            "synopsis": "Akuto dreams of being a magician, but a test predicts that he&#39;ll become a Demon King instead -- a fate that creates problems at his new school.",
            "rating": "4.061274",
            "year": "2010",
            "runtime": "0",
            "imdb_id": "tt1636694",
            "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BZmRjZjgxZGQtZmFhZi00NjI2LTkzMWUtMDI1OTU3ZTI0ZGY1XkEyXkFqcGdeQXVyMjQ5NjMxNDA@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2016-04-01"
        },
        {
            "title": "True North",
            "img": "https://occ-0-988-993.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABVK6r6JcIKU9RgvHyzmd9d4X_RDu3EbVXBPUmnz12wHCYhDQK8ykMCuucORXz6FEkQ2GRf8hyOllk_FbFB2Cfu9rKg.jpg?r=38b",
            "title_type": "movie",
            "netflix_id": 81509442,
            "synopsis": "While wrongfully imprisoned in a labor camp, a young boy from Pyongyang faces daily atrocities that test his belief in the innate goodness of others.",
            "rating": "0",
            "year": "2020",
            "runtime": "5630",
            "imdb_id": "tt0497365",
            "poster": "https://m.media-amazon.com/images/M/MV5BMTYyMjE1MzI2Ml5BMl5BanBnXkFtZTcwNjA1OTY0MQ@@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2021-11-04"
        },
        {
            "title": "Gurushetram: 24 Hours Of Anger",
            "img": "https://occ-0-58-64.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABRyoUEWZTeQ2sDBKjctFf_uC8k5LCWBNS8oB4GRslAKAepFvSH7_Mj35F0eYisiEffu8spvUwQpPYUAEJyofCbrfsw.jpg?r=da9",
            "title_type": "movie",
            "netflix_id": 81310411,
            "synopsis": "A teen’s efforts to protect his younger brother becomes a test for survival as the two draw the ire of the Singaporean underworld and the authorities.",
            "rating": "0",
            "year": "2010",
            "runtime": "7649",
            "imdb_id": "tt1671571",
            "poster": "https://m.media-amazon.com/images/M/MV5BMTU1OTkxMDQ5MV5BMl5BanBnXkFtZTcwNDg0NDI2Mw@@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2020-09-05"
        },
        {
            "title": "The Brand New Testament",
            "img": "https://occ-0-1007-1360.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABWmZdcOiZBc7SMC-73RfaNu10uAqA5vl3sjCR3HfyyJOTZU0ImtUV7upM02NbHaZjv1k6wQKuXR7A2vrSZB4WPZ4iw.jpg?r=7b6",
            "title_type": "movie",
            "netflix_id": 80060035,
            "synopsis": "In this irreverent comedy, God torments humanity from his apartment in Brussels -- until his daughter rebels and texts everyone their date of death.",
            "rating": "0",
            "year": "2015",
            "runtime": "6874",
            "imdb_id": "tt3792960",
            "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMjM3OTAzMzYzNV5BMl5BanBnXkFtZTgwNTQ4MzU0MDI@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2017-12-29"
        },
        {
            "title": "Lego Friends: Girls on a Mission",
            "img": "https://occ-0-2851-38.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABe-sffRF-DEJGJUOGwuFvYW2ID1J6A0I9v_e-GzlLq4hCgiGKyuSgwldCQaE2FxmULJ-4EJCKZR06cT55Ez8jvhYZw.jpg?r=bc7",
            "title_type": "series",
            "netflix_id": 81050118,
            "synopsis": "Five best friends put their teamwork, wits and courage to the test when they take on a mission to protect Heartlake City from bad people.",
            "rating": "0",
            "year": "2018",
            "runtime": "0",
            "imdb_id": "tt9327146",
            "poster": "https://m.media-amazon.com/images/M/MV5BNGU5MjI2MWEtNjhmYi00YjU5LTg1N2QtM2Y4NjU4MzhiYjcwXkEyXkFqcGdeQXVyMTY3MzYyMjA@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2019-02-01"
        },
        {
            "title": "Sometimes",
            "img": "https://occ-0-2851-38.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABWXwCHZQ1usdIp58V1_QF40ZV-EwzISHYmt6sT02ApfaTTilzZf54nByLJc0bxGqQWVFjiBlUkcGMdSrNsViFyPx9aEQF0VKGfGKN6w4Li2XLwc6BcGaSygTxI0.jpg?r=69e",
            "title_type": "movie",
            "netflix_id": 80228322,
            "synopsis": "Seven strangers anxiously waiting for their HIV test results decide to bribe the clinic receptionist to get them early, learning one is positive.",
            "rating": "0",
            "year": "2016",
            "runtime": "6075",
            "imdb_id": "tt5877882",
            "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BZWEyYzViNGMtOWQyOC00OTk4LWE0NGEtNTMyNDk2ZTZkNDIyXkEyXkFqcGdeQXVyMTU2OTI0Mzg@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2018-05-01"
        },
        {
            "title": "The Age of Innocence",
            "img": "https://occ-0-1926-41.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABXijKbiDxi7birb2Om3M7CLnZhZ9w-5w_VV5kORCaXaonqbse3DNDFLWbpOa_B2lmQuTtOmtZ9Zandwf6vz-AX7W7g.jpg?r=81f",
            "title_type": "movie",
            "netflix_id": 60011002,
            "synopsis": "A well-bred New Yorker engaged to an appropriate, cultured woman puts society&#39;s mores to the test when her alluring cousin comes along.",
            "rating": "3.4256094",
            "year": "1993",
            "runtime": "8306",
            "imdb_id": "tt0106226",
            "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMWEzM2Y0MmYtOGE3OS00MTdiLWFlYjctZWE0OTU0NzEzOTIwXkEyXkFqcGdeQXVyNjUwNzk3NDc@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2015-04-14"
        },
        {
            "title": "FYRE: The Greatest Party That Never Happened",
            "img": "https://occ-0-2717-360.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABc7-ohnAVTOTHqY3iRrySPLBj7_p9jlyHUYEpATFmfTXjLM98n1KQcX-cCin3KED8J41fc6HrQtAxrH_0EapApDSRN4_QoScstow_5TynzUKbzRJ7lAFRpbo7js.jpg?r=11a",
            "title_type": "movie",
            "netflix_id": 81035279,
            "synopsis": "The Fyre Festival was billed as a luxury music experience on a posh private island, but it failed spectacularly in the hands of a cocky entrepreneur.",
            "rating": "0",
            "year": "2019",
            "runtime": "5861",
            "imdb_id": "tt9412098",
            "poster": "N/A",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2019-01-18"
        },
        {
            "title": "The Day the Earth Caught Fire",
            "img": "https://occ-0-5169-2774.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABcwFKKtqAdg13Zs1orkN1AQBJ8zTDMr5tSkV8SvVOhelZ5iRDUtnnG9J5PJELZZBIvjhUZKzx448-Wp_nQMhafchNg.jpg?r=02c",
            "title_type": "movie",
            "netflix_id": 70000217,
            "synopsis": "When the US and Soviet Union unwittingly test nuclear weapons at the same time, scientists race to save Earth from catastrophe.",
            "rating": "0",
            "year": "1961",
            "runtime": "5962",
            "imdb_id": "tt0054790",
            "poster": "https://m.media-amazon.com/images/M/MV5BZjZmYTUxZDktZDA5YS00OTE0LWFjZWItNjc1ZDU1Mjg5YmIyXkEyXkFqcGdeQXVyMjI4MjA5MzA@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2022-01-01"
        },
        {
            "title": "Jimmy Carr: The Best of Ultimate Gold Greatest Hits",
            "img": "http://occ-0-2851-38.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABVPO1ATd7-qDsJmswXSRCaUHTjZK80pKIkN6zu_1xDufXaAYCAv5kgF09hDIGA_L4ZgWEmVTbWwSzAxxS2Ckr0obO4QHAVHlbAB-7Yhs1vuRtPMC3NRZeiexDuw.jpg?r=d7d",
            "title_type": "movie",
            "netflix_id": 80214087,
            "synopsis": "Nothing is off limits as Jimmy Carr serves up the most outrageous jokes from his stand-up career in a special that&#39;s not for the faint of heart.",
            "rating": "0",
            "year": "2019",
            "runtime": "3490",
            "imdb_id": "tt9817258",
            "poster": "N/A",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2019-03-12"
        },
        {
            "title": "Greatest Gift of Life",
            "img": "https://occ-0-993-988.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABeO0w7Fbq1Gk706v7zCwRNdDqdK9B2ym4nQyKbB7CDx4gWEavwi1J0CsaeDaWxj0DeC61AkyVHpmV87tIHGtOZDKpQ.jpg?r=a5e",
            "title_type": "movie",
            "netflix_id": 81446804,
            "synopsis": "Yuriko returns home to Tokyo to live with her widowed father — much to his surprise. Unbeknownst to him, she’s living with a terminal illness.",
            "rating": "0",
            "year": "2021",
            "runtime": "5451",
            "imdb_id": "tt13522030",
            "poster": "https://m.media-amazon.com/images/M/MV5BYzE2NjcwNjItYTFiMC00NTVkLWJjMTYtMmVhODNmNjUyYjgzXkEyXkFqcGdeQXVyMzQ5MzAyMzI@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2021-07-05"
        },
        {
            "title": "Clergy",
            "img": "https://occ-0-2506-1432.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABTW66OVW2rI4rTonAMmSLRLaSXnyIW5zTXP9FzwqwqXBIo-RiS_e8E4JxvcWkprhpsHujLheaGU5SfEsMR6wCIV6NA.jpg?r=b9b",
            "title_type": "movie",
            "netflix_id": 81168900,
            "synopsis": "Linked by tragedy and time, three flawed Catholic priests hurtle toward a test of faith as they live their lives more as sinners than saints.",
            "rating": "0",
            "year": "2018",
            "runtime": "7767",
            "imdb_id": "tt8738964",
            "poster": "https://m.media-amazon.com/images/M/MV5BMDNmZjlkMjMtYjlkMi00NTM5LTk1ZmUtNzJiNDI3NTI0ZDM0XkEyXkFqcGdeQXVyMjMwOTA0Ng@@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2020-03-01"
        },
        {
            "title": "The Island with Bear Grylls",
            "img": "https://occ-0-5064-299.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABUZE-zopP5TXmkvgiMeGfj6sP8k-p2qyNLfHA3AYUqaXuCDlu1hnPFs-axvxl2GUig1No3IkkJa3C0Wl0IcHpb_6Mg.jpg?r=dc6",
            "title_type": "series",
            "netflix_id": 81539355,
            "synopsis": "Bear Grylls narrates this reality show in which participants test their survival skills on a remote island for several weeks.",
            "rating": "0",
            "year": "2019",
            "runtime": "0",
            "imdb_id": "tt3725394",
            "poster": "https://m.media-amazon.com/images/M/MV5BYjBiM2JkMzMtNzYyNC00ZjJjLTgwZTItZTRiMmIyMzM2Y2ZmXkEyXkFqcGdeQXVyMjYwNDA2MDE@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2021-12-22"
        },
        {
            "title": "Bokurano",
            "img": "https://occ-0-1007-1360.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABXuMtfzNy-Ap_TLTJQKP-qHDQ375MEB2iiJBHBKTK8wIWggrYn1ME2qXbqNHtNNlvM4Kx3cvzHk_Qh4pAf2xO9IxAQ.jpg?r=352",
            "title_type": "series",
            "netflix_id": 80133772,
            "synopsis": "Fifteen middle schoolers agree to test the game that a is creating in a seaside cave and find themselves defending Earth from giant robots.",
            "rating": "2.8648648",
            "year": "2007",
            "runtime": "0",
            "imdb_id": "tt1132201",
            "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BYmQ5ZjE4NDEtZDIwMC00MTlmLWI4ODgtOGMzZWZhYzk4NGRiXkEyXkFqcGdeQXVyNjY1MTU1MjA@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2016-11-01"
        },
        {
            "title": "The Annulment",
            "img": "https://occ-0-1892-64.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABXdGlAJ2C-0V4aHZPZXyd6_AbjyMMRfdL6PMDZHqKrL1NCyas75zRs3BcU0LR2dW98vDbKAb3YheA4GbZgfEXEFY0w.jpg?r=415",
            "title_type": "movie",
            "netflix_id": 81310421,
            "synopsis": "Two strangers from different worlds fall in love and get married until familial pressures and personal failures begin to test their relationship.",
            "rating": "0",
            "year": "2019",
            "runtime": "6642",
            "imdb_id": "tt11091632",
            "poster": "https://m.media-amazon.com/images/M/MV5BZjdlMzE4NTMtM2UyMi00OWQ2LTkzMjktNWI3MTA5MWQxZDQzXkEyXkFqcGdeQXVyNTI5NjIyMw@@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2021-04-12"
        },
        {
            "title": "The Cruel Sea",
            "img": "https://occ-0-5169-2774.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABTkvixc83d3LGKnzAR25f_JL4Xrdna_SCHDYvSGV02vZWJGdHT_1z8hG88iiFBgR5j2HzwILxzgmVFsTvTvmp4Ckzg.jpg?r=0dd",
            "title_type": "movie",
            "netflix_id": 60011076,
            "synopsis": "WWII Lieutenant Commander Ericson&#39;s abilities get put to the test when he must lead his ship’s inexperienced crew during the Battle of the Atlantic.",
            "rating": "0",
            "year": "1953",
            "runtime": "7583",
            "imdb_id": "tt0045659",
            "poster": "https://m.media-amazon.com/images/M/MV5BOGE3YjRkMDAtZjdkNS00MGZmLWJmYmMtYmU3OWU2ZGVkNzZhXkEyXkFqcGdeQXVyMzg1ODEwNQ@@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2022-01-01"
        },
        {
            "title": "A Better Tomorrow",
            "img": "https://occ-0-64-325.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABR9OqBTV6OPtgBA8vl0-GLnRNjAalCIlTok9cmdxWHEND8UH405e2Uv8LS6EUu3NYHP0l8h0qAHiF1hmrQyMInfXow.jpg?r=b7c",
            "title_type": "movie",
            "netflix_id": 60024206,
            "synopsis": "Two brothers, each on opposite sides of the law, find their worlds colliding when their father is murdered and their loyalties are put to the test.",
            "rating": "0",
            "year": "1986",
            "runtime": "5755",
            "imdb_id": "tt0092263",
            "poster": "https://m.media-amazon.com/images/M/MV5BZTEzMTYwZDItODIyYy00MjRkLTljOWMtZDI0ZmNjN2JjOTEyXkEyXkFqcGdeQXVyNzgzODI1OTE@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2018-11-16"
        },
        {
            "title": "Rock and Roll&#39;s Greatest Failure: Otway the Movie",
            "img": "https://occ-0-1698-1348.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABUGPmmhParxG24NUfuiB4CRx58ztLuBnRLhRJysZO9S9W_4yhJRthlO_eW15Sy1348AuERed7NLvU1uXGVj0S_iJGw.jpg?r=1a8",
            "title_type": "movie",
            "netflix_id": 81408998,
            "synopsis": "This documentary chronicles the colorful life of singer-songwriter John Otway, his relentless optimism and his hairbrained schemes to mount a comeback.",
            "rating": "0",
            "year": "2013",
            "runtime": "5786",
            "imdb_id": "tt0122689",
            "poster": "https://m.media-amazon.com/images/M/MV5BNjc0Njg4MzU1Nl5BMl5BanBnXkFtZTcwMjgyMTcyMQ@@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2021-09-30"
        },
        {
            "title": "18 Grams of Love",
            "img": "https://occ-0-58-2773.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABeGofHtFlZohP82FsrA3BuwdhlGtCCThEywNEVVKtPhKErD1Z5Xo1jA91Aa7DjYmZQLtWlnUKyDbsDRNtHi9TdObfg.jpg?r=25f",
            "title_type": "movie",
            "netflix_id": 81295039,
            "synopsis": "To test their wives&#39; fidelity, two friends decide to write them anonymous love letters — which lead to unintended consequences.",
            "rating": "0",
            "year": "2007",
            "runtime": "5059",
            "imdb_id": "tt1127682",
            "poster": "https://m.media-amazon.com/images/M/MV5BYmE4NDNkMDEtZjNmZS00Y2Y5LThhZjEtOTFjODQ0ZDBkZjc2XkEyXkFqcGdeQXVyMjg0MTI5NzQ@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2020-08-02"
        },
        {
            "title": "Buddy Thunderstruck: The Maybe Pile",
            "img": "https://occ-0-2851-38.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABRa9sFLpe0JkXTN1D1gGta0Gf1AesT3DnQK46rp4D84D4mpbBYAxRnXTi3hzouJ46ODeSNs6v17rOXWnvK8qwNAd3nci7NNVxisJkQSlDxw3vCmTBSCZEnxGPqmJ1KW7A0NeWPwvP0jREgYz11CAth-apDiPfFlJzdKdFxqkx5v62t27FVrBjw.jpg?r=e7e",
            "title_type": "movie",
            "netflix_id": 80149064,
            "synopsis": "Champion truck-racing dog Buddy and his best friend, ferret mechanic Darnell, paw through the &#39;maybe pile&#39; and test out a bunch of crazy stunts.",
            "rating": "0",
            "year": "2017",
            "runtime": "815",
            "imdb_id": "tt7094950",
            "poster": "",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2017-07-14"
        },
        {
            "title": "All American",
            "img": "https://occ-0-2219-2218.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABRkCIBxM7Odvfohs637mOsIcWSQvLN98KvmlxXqROGRY3OuU3mFdfLOLk2qzA1dOMZg-r79wH18bhWqkqc0I5qv0dw.jpg?r=50e",
            "title_type": "series",
            "netflix_id": 81012998,
            "synopsis": "Culture clashes and brewing rivalries test a teen football player from South Los Angeles when he’s recruited to the Beverly Hills High School team.",
            "rating": "0",
            "year": "2019",
            "runtime": "0",
            "imdb_id": "tt7414406",
            "poster": "https://m.media-amazon.com/images/M/MV5BNjI2YWIwZWMtMmIyZC00NTA2LTlhYmItZDY4ZWM1YTI1NzE4XkEyXkFqcGdeQXVyMzU3MTc5OTE@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2019-03-28"
        },
        {
            "title": "Sungkyukwan Scandal",
            "img": "https://occ-0-1007-1360.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABTGoy_Zl0jjdy8B9Aab-h6qViIQ_4Kx9qzCcA4L0w4rotjBMkQnAWpvtU3Q4lREJGLGnP6a37O6rW0mp-y8zNslJxw.jpg?r=f5c",
            "title_type": "series",
            "netflix_id": 80154882,
            "synopsis": "In the Joseon dynasty, a female breadwinner takes a job as a substitute test-taker, but soon finds herself attending a men&#39;s university in disguise.",
            "rating": "3",
            "year": "2010",
            "runtime": "0",
            "imdb_id": "tt2745682",
            "poster": "http://ia.media-imdb.com/images/M/MV5BMmI5Nzk1NGMtM2E1ZS00OTk2LWJlMDQtYTdkMmE4OGE2ZjRlXkEyXkFqcGdeQXVyMzE4MDkyNTA@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2017-02-17"
        },
        {
            "title": "Bloodline",
            "img": "https://occ-0-2851-38.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABbq8a92YPL3VRW-WCLbQlPv7hpN2lsEspmgMJKtsKUXFEGWcJh-ruqNHyeuQ40-iupAa7VOcgz8i_aYsvvF98MMBbNFhwumAZ-7ctxG3nKQlKT05Dv5xEwWUX0A.jpg?r=4f0",
            "title_type": "series",
            "netflix_id": 80010655,
            "synopsis": "When the black sheep son of a respected family threatens to expose dark secrets from their past, sibling loyalties are put to the test.",
            "rating": "4.1707983",
            "year": "2015",
            "runtime": "0",
            "imdb_id": "tt3520702",
            "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTU4OTY0MzM1OV5BMl5BanBnXkFtZTgwMjkxMzE0MjI@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2015-04-14"
        }
    ]
    const search = useSelector(state => state.search)
    const [movies,setMovies] = useState(dark)
    const dispatch = useDispatch()

    const handleOnSubmit = () => {
    var options = {
        method: 'GET',
        url: 'https://unogs-unogs-v1.p.rapidapi.com/search/titles',
        params: {title: search, order_by: 'rating', limit: '100'},
        headers: {
            'x-rapidapi-host': 'unogs-unogs-v1.p.rapidapi.com',
            'x-rapidapi-key': process.env.REACT_APP_REACT_KEY
        }
      };
      dispatch(APIADD())
      axios.request(options).then(function (response) {
              console.log(response.data.results.filter(movie => movie.img));
              setMovies(response.data.results.filter(movie => movie.img))
              dispatch(UPDATEMOVIELIST(response.data.results.filter(movie => movie.img)))
      }).catch(function (error) {
          console.error(error);
      });
    }

    useEffect(() => {
        handleOnSubmit()
      }, [search]); // Only re-run the effect if count changes

    // let extraImg = (movies.map(movie => movie.netflix_id))
    let moviesWithPictureOnly = (movies.filter(movie => !movie.img))
    // console.log(moviesWithPictureOnly)
    
    return (
        <div>
            {
            movies 
            ? <div className='movieDisplay'>
                {movies.map(movie =>
                    <div key={movie.title+movie.netflix_id} >
                        <MovieDisplay movie={movie} />
                    </div>
                    )
                }
            </div> 
       
            :<h1>There are no search result for this movie</h1>
            }

        </div>
    )
}

export default MovieMain